name: shellcheck

on: [push]

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: ShellCheck Action
        uses: fearphage/shellcheck-action@0.0.3
